### ISSUE TITLE
Encoding issues on Windows

### ISSUE THREAD

**Issue by Rubyfi** [boschglobal/doxysphinx#108]
When running doxysphinx 3.3.0 on Windows, the following error occurs:
```
Traceback (most recent call last):
 ...
  File "c:\...\Python310\Lib\site-packages\doxysphinx\resources.py", line 221, in scope
    css_content = stylesheet.read_text()
  File "pathlib.py", line 1133, in read_text
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 27474: character maps to <undefined>
```
This seems to be, because pathlib assumes cp1252 as the default encoding when running on Windows.
It did some investigating, and the issue can be fixed by replacing [this line](https://github.com/boschglobal/doxysphinx/blob/main/doxysphinx/resources.py#L221) with the following:
`css_content = stylesheet.read_text(encoding='UTF-8')`

**Comment by jofo235** [comment]
Hello! I still get an error with Doxysphinx 3.3.3:

`(od) C:\dev\pj-dc_int\dc_fw\src\dsm\doc\sphinx-needs>doxysphinx build ./source ./build/html ./source/doxygen/_build/html
doxysphinx v3.3.3
starting build command...
Traceback (most recent call last):
  File "C:\Users\foo2lr\.conda\envs\od\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\foo2lr\.conda\envs\od\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\foo2lr\.conda\envs\od\Scripts\doxysphinx.exe\__main__.py", line 7, in <module>
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\doxysphinx\cli.py", line 135, in build
    builder.build(doxy_output)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\doxysphinx\process.py", line 87, in build
    copied_resources = self._resource_provider.provide_resources(doxygen_html_dir)
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\doxysphinx\resources.py", line 141, in provide_resources
    written_doxygen_awesome_css = self._css_scoper.scope(
  File "C:\Users\foo2lr\.conda\envs\od\lib\site-packages\doxysphinx\resources.py", line 258, in scope
    target.write_text(compiled_css)
  File "C:\Users\foo2lr\.conda\envs\od\lib\pathlib.py", line 1256, in write_text
    return f.write(data)
  File "C:\Users\foo2lr\.conda\envs\od\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6777-6778: character maps to <undefined>

(od) C:\dev\pj-dc_int\dc_fw\src\dsm\doc\sphinx-needs>`

**Comment by twodrops** [comment]
@jofo235 Thanks for the bug report. Could you also please confirm your python version?

@mb-emag I am reopening this as the issue is reproducible on Windows with Doxysphinx 3.3.3.

**Comment by jofo235** [comment]
This fix seemed to work! Thank you!

**Comment by sky-dream** [comment]
> Specifying the encoding might do the trick here as well. Could you try changing line 258 in `C:\Users\foo2lr.conda\envs\od\lib\site-packages\doxysphinx\resources.py` from
> 
> ```
> target.write_text(compiled_css)
> ```
> 
> to
> 
> ```
> target.write_text(compiled_css, encoding="UTF-8")
> ```

the similar error happened in my side also as below ,
```
doxysphinx v3.3.3
File "C:\xxxxx\Python310\Lib\site-packages\doxysphinx\process.py", line 154, in _run
    parse_result = parser.parse(html_file)
  File "C:\xxxxxx\Python310\Lib\site-packages\doxysphinx\html_parser.py", line 487, in parse
    buffer = file.read_text()
  File "pathlib.py", line 1133, in read_text
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 627375: character maps to <undefined>
```
With this walk around, it is still not work , with some additional adaptation as below, it works.
```
File path: xxxx\Python310\Lib\site-packages\doxysphinx\html_parser.py
```
```py
def parse(self, file: Path) -> HtmlParseResult:
        buffer = file.read_text(encoding='UTF-8')
```
