### ISSUE TITLE
doxysphinx crashed due to UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d

### ISSUE THREAD

**Issue by sky-dream** [boschglobal/doxysphinx#147]
**Describe the bug**
when using the doxysphinx v3.3.7 to build the documents from the doxygen result, it pops the encoding and decoding error as below,
**UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d** in position 2337: character maps to <undefined>

**Expected behavior**
doxysphinx tool should not get crashed, it should catch up this exception, log it in the console, or in a log file, 
and put some question mark for corresponding unknown chars in the generated docuement.

**Additional context**
more detail trace back error log can be found as below,

Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Python310\Scripts\doxysphinx.exe\__main__.py", line 7, in <module>
  File "C:\Python310\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python310\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\Lib\site-packages\doxysphinx\cli.py", line 135, in build
    builder.build(doxy_output)
  File "C:\Python310\Lib\site-packages\doxysphinx\process.py", line 92, in build
    created_rsts = self._build(doxygen_html_dir)
  File "C:\Python310\Lib\site-packages\doxysphinx\process.py", line 97, in _build
    writer = self._writer_type(doxygen_html_dir)
  File "C:\Python310\Lib\site-packages\doxysphinx\writer.py", line 76, in __init__
    self._toc_gen = toc_generator_type(source_directory)
  File "C:\Python310\Lib\site-packages\doxysphinx\toc.py", line 150, in __init__
    self._doxy_html_template: Tuple[str, str] = self._parse_template()
  File "C:\Python310\Lib\site-packages\doxysphinx\toc.py", line 168, in _parse_template
    complete_html = blueprint.read_text()
  File "pathlib.py", line 1133, in read_text
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2337: character maps to <undefined>
2024-07-16 09:07:18 - doxysphinx_build_log - ERROR
--------------------------------------------------
DoxySphinx Build failed, check the log above for error messages.

**Comment by sky-dream** [comment]
After the investigation, i just found the problem is result from ** “ **, its encode value as below, 
The **'RIGHT DOUBLE QUOTATION MARK' (U+201D) ”** is encoded in UTF-8 with bytes 0xE2 0x80 0x9D. 

Another similar character maybe also result problem, its encode value as below,
The 'RIGHT SINGLE QUOTATION MARK' (U+2019) ’ is encoded in UTF-8 with bytes 0xE2 0x80 0x99.

These 2 characters maybe not often used in the English text, but it is popular in the Chinese text.

It would be nice that Doxysphinx can take a good exception handling for that, tks.
